
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6IkNVU1RPTUVSIiwiaWF0IjoxNzY0MzM2MDQyLCJleHAiOjE3NjQ5NDA4NDJ9.nnZ0_wpxqkmP92eyS6YSUqu81Sz_7ApOxw4Yl_uX4jA


@admin_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY0MzM1OTE3LCJleHAiOjE3NjQ5NDA3MTd9.GDQMoGU3QMVl4rzb87HJB4rqsocaAjLAodCO2q0mz_c


### Create Order (from Cart)
POST http://localhost:5000/api/v1/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{}

### Get My Orders
GET http://localhost:5000/api/v1/orders
Authorization: Bearer {{token}}

### Get Order Details
GET http://localhost:5000/api/v1/orders/1
Authorization: Bearer {{token}}

### Update Order Status (Admin)
PUT http://localhost:5000/api/v1/orders/1/status
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "status": "SHIPPED"
}
